### ISSUE TITLE
re-export sqlite3 common as well

### ISSUE THREAD

**Issue by wildsylvan** [powersync-ja/powersync.dart#109]
the latest changes require `CommonDatabase` (e.g. to override some methods in `PowerSyncOpenFactory`) but `CommonDatabase` is not available [here](https://github.com/powersync-ja/powersync.dart/blob/0d63063446e7a4a296cc7491fa20edde7c3aade9/packages/powersync/lib/sqlite3.dart). what about re-exporting [sqlite3_common.dart](https://github.com/powersync-ja/sqlite_async.dart/blob/26315e1e5c8e9b7ea25c70db93e0cfe5604bf888/lib/sqlite3_common.dart) from powersync?

**Comment by mugikhan** [comment]
> the latest changes require `CommonDatabase` (e.g. to override some methods in `PowerSyncOpenFactory`) but `CommonDatabase` is not available [here](https://github.com/powersync-ja/powersync.dart/blob/0d63063446e7a4a296cc7491fa20edde7c3aade9/packages/powersync/lib/sqlite3.dart). what about re-exporting [sqlite3_common.dart](https://github.com/powersync-ja/sqlite_async.dart/blob/26315e1e5c8e9b7ea25c70db93e0cfe5604bf888/lib/sqlite3_common.dart) from powersync?

Hi while we look at this would it not be possible to import it from the `sqlite_async` package as that is also exported from powersync?

`import 'package:sqlite_async/sqlite3_common.dart';`

**Comment by mugikhan** [comment]
@wildsylvan Thanks for reporting this. We have exposed `sqlite3_common` in powersync v1.5.1 (#112). Please let us know if you have any other concerns.
