### ISSUE TITLE
`PowerSyncDatabase.waitForFirstSync()` introduced in 1.5.1, present through 1.5.5, has gone missing in 1.6.0

### ISSUE THREAD

**Issue by nurturenature** [powersync-ja/powersync.dart#131]
Hi,

`PowerSyncDatabase.waitForFirstSync()` was introduced in 1.5.1, is present through 1.5.5, and has gone missing in 1.6.0.

P.S. Can also confirm that `waitForFirstSync()` has been working well since its refactor in 1.5.2.

Thanks.

**Comment by mugikhan** [comment]
@nurturenature Thanks for reporting this, it has gone missing between the merge from alpha to master. We working on adding it back in v1.6.1.

**Comment by mugikhan** [comment]
@nurturenature We have just published PowerSync v1.6.1 which should include the `waitForFirstSync()` API. Thanks for reporting this.
