### ISSUE TITLE
Can't initialize db except on web: Unsupported powersync extension version. Need ˆ0.2.0, got 0.1.6/14f7c2b0*

### ISSUE THREAD

**Issue by selimb86** [powersync-ja/powersync.dart#156]
Hello,

I have implemented powersync with success a time ago and not used much because the web was not supported. 

Today I tried to update it and use in web and all worked fine. that's great ! But when tried to test mobile platforms (iOS & Android) while using the correct paths as in the docs the app in hanging on db.initialize() while the path is correct.

If I remove the initialize part I have an error stating that "**SqliteException(1): Unsupported powersync extension version. Need ˆ0.2.0, got 0.1.6/14f7c2b0**".

`
Future<String> getDatabasePath() async {
  String path;

  if (!kIsWeb) {
    final dir = await getApplicationSupportDirectory();
    path = join(dir.path, 'noqta-1.db');
  } else {
    path = 'noqta.db';
  }

  Logger().d('[PowerSync] Database path: $path');
  return path;
}
`

Tried version 1.7.0, 1.6.3 and 1.5.5 and still the same problem.

**Comment by rkistner** [comment]
Thanks for reporting, it's likely an issue with v1.8.0. Use version 1.7.0 until we fix the issue, but make sure you install exactly 1.7.0 and not ^1.7.0.

**Comment by selimb86** [comment]
Thanks it works now 👍

**Comment by rkistner** [comment]
Fixed in v1.8.1

**Comment by selimb86** [comment]
Thanks !
