### ISSUE TITLE
Setup web is not working

### ISSUE THREAD

**Issue by richard457** [powersync-ja/powersync.dart#158]
dart run powersync:setup_web
Building package executable... 
Built powersync:setup_web.

Using package:powersync from /Users/name/.pub-cache/hosted/pub.dev/powersync-1.8.2
Downloading: https://github.com/powersync-ja/powersync.dart/releases/download/powersync-v1.8.2/powersync_db.worker.js
Exception: Failed to download file: 404 Not Found

**Comment by richard457** [comment]
The link does not work it should be https://github.com/powersync-ja/powersync.dart/releases/powersync-v1.8.2/powersync_db.worker.js  I guess??

**Comment by rkistner** [comment]
Thanks for the report!
It was an issue with the 1.8.2 release, should be fixed now.

**Comment by richard457** [comment]
It is fixed @rkistner any resource on how to self-host powersync with a tool like terraform?

**Comment by cahofmeyr** [comment]
Hi @richard457, we don't currently have specific guides like that, but it is something that we are planning to add. 

https://docs.powersync.com/self-hosting/getting-started
