### ISSUE TITLE
Please update 'sqlite_async' dependency

### ISSUE THREAD

**Issue by AlexanderBykin** [powersync-ja/powersync.dart#160]
Hi

It looks like you are using old dependency "sqlite_async: ^0.8.3" which based on "web: ^0.5.1" that is imcompatible to be used with another "auto_route: ^9.2.2" dependency which based on "web: ^1.0.0"

could you please update sqlite_async to 0.9.0 version?

**Comment by JavascriptMick** [comment]
Hi @AlexanderBykin please share a working set of dependencies.  when I try sqllite_async 0.9.0, I get this error...
```
Resolving dependencies...
Because powersync 1.8.2 depends on sqlite_async ^0.8.3 and no versions of powersync match >1.8.2 <2.0.0, powersync ^1.8.2 requires sqlite_async ^0.8.3.
So, because trolleymate_app depends on both powersync ^1.8.2 and sqlite_async ^0.9.0, version solving failed.
```

**Comment by AlexanderBykin** [comment]
@JavascriptMick You should ask not me, but the author of this library, he is the one who should decide this question

**Comment by AlexanderBykin** [comment]
@mugikhan can you please provide working solution?

**Comment by mugikhan** [comment]
Hey @AlexanderBykin, we currently do not support web v1.0.0 in `sqlite_async`. Updating that version conflicts with other dependencies such as `drift`. We are aware of this and will make the required updates to support `package:web` v1.0.0. In the meantime, please use `auto_route: 9.2.0` or lower.

**Comment by selimb86** [comment]
The same happens with `flutter_quill`

**Comment by JCKodel** [comment]
Not a fix, but, if you are **not** using web builds, this let you compile the app (tested on Android and iOS):

```yaml
dependency_overrides:
  web: 1.0.0
```

**Comment by mugikhan** [comment]
Hey @AlexanderBykin @JavascriptMick @selimb86 `sqlite_async` has been updated to version 0.9.0 in `powersync: ^1.8.6`. 

Huge thanks to @davidmartos96 for creating the respective PRs across multiple projects to get this done.

**Comment by AlexanderBykin** [comment]
@mugikhan @davidmartos96 nice job, thanks!
