### ISSUE TITLE
supabase-todolist Demo App - SupabaseConnector does not need a db instance

### ISSUE THREAD

**Issue by JavascriptMick** [powersync-ja/powersync.dart#165]
Pretty sure there is an unnecessary and, frankly confusing mistake in the supabase-todolist demo code.

e.g. this file....
https://github.com/powersync-ja/powersync.dart/blob/main/demos/supabase-todolist/lib/powersync.dart

From Line 28
```Dart
class SupabaseConnector extends PowerSyncBackendConnector {
  PowerSyncDatabase db;

  Future<void>? _refreshFuture;

  SupabaseConnector(this.db);
```

the db instance is *not* used inside the class or by users of the class.  Smells like a refactor happened and this was left in.  I was able to rip the property out and run the demo app just fine...

```Dart
class SupabaseConnector extends PowerSyncBackendConnector {
  Future<void>? _refreshFuture;

  SupabaseConnector();
```

**Comment by mugikhan** [comment]
Thanks for reporting this @JavascriptMick we've removed the unnecessary db instances in the connectors for all the demos.
