### ISSUE TITLE
Detect unsupported 32-bit environments

### ISSUE THREAD

**Issue by kobiebotha** [powersync-ja/powersync.dart#166]
Running on an x86 Android emulator results in an error:

`'Unsupported processor architecture. X86 Android emulators are not supported. Please use an x86_64 emulator instead. All physical Android devices are supported including 32bit ARM.',`

The SDK is not catching this exception - it should, and then show a helpful error message to the user.

**Comment by rkistner** [comment]
What is the difference between the current and expected behavior there? The message above already seems helpful to me

**Comment by mugikhan** [comment]
> What is the difference between the current and expected behavior there? The message above already seems helpful to me

The message from the exception did not display to the user in the stacktrace. Addressed in #170 and will be fixed in the next release.
