### ISSUE TITLE
Malformed framework error when trying to upload on mac AppStore

### ISSUE THREAD

**Issue by stevenosse** [powersync-ja/powersync.dart#197]
Hi
I tried to upload an app on the Appstore and i got these error messages from Apple:

**ITMS-90291:** Malformed Framework - The framework bundle (YourApp.app/Contents/Frameworks/powersync-sqlite-core.framework) must contain a symbolic link 'powersync-sqlite-core' -> 'Versions/Current/powersync-sqlite-core'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information.

**ITMS-90291:** Malformed Framework - The framework bundle (YourApp.app/Contents/Frameworks/powersync-sqlite-core.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information.

**ITMS-90292:** Malformed Framework - The framework bundle (YourApp.app/Contents/Frameworks/powersync-sqlite-core.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the [Anatomy of Framework Bundles](http://developer.apple.com/library/mac/#documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) for more information.

# Environment
powersync: ^1.8.7

## Flutter doctor output
<img width="967" alt="Capture d’écran 2024-10-18 à 17 38 03" src="https://github.com/user-attachments/assets/81ed2776-ef70-4823-b8e3-61247736fb26">

**Comment by rkistner** [comment]
To be clear, is this for an iOS or macOS app?

**Comment by stevenosse** [comment]
It's for a macOS app

**Comment by mugikhan** [comment]
Hey @stevenosse and @alterhuman, This has been fixed in PowerSync v1.8.8. Please let me know if you still have the malformed framework issues.
> Note: When developing, you will need to install the pods using `pod install --repo-update` in order to get the latest `powersync-sqlite-core` pod

**Comment by stevenosse** [comment]
It worked. Closed the issue as it's fixed.
