### ISSUE TITLE
Question: why PowerSyncBackendConnector sometimes receive part of changed row at uploadData method

### ISSUE THREAD

**Issue by AlexanderBykin** [powersync-ja/powersync.dart#199]
Hi

When I change some fields in some record from my table, sometimes all the fields of the changed record come to the "PowerSyncConnector.uploadData" method, and sometimes only the changed fields, I can't figure out the pattern.

Question: how to control the field return mechanism?

p.s. our backend is implemented in such a way that if the fields did not come from the client, then "null" must be written to them

**Comment by michaelbarnes** [comment]
@AlexanderBykin When changes on individual fields are made, the transaction `op` should be `PATCH` and the `opData` will contain an object that only has the changed fields. When creating new rows in a table the `op` should be `PUT` and the `opData` should contain an object with all the fields. 

Here are a few logs from a test app using the latest version of the PowerSync dart package:

Insert Row:
`CrudTransaction<6, [CrudEntry<6/6 PUT todos/4e5dd005-7b5d-44be-ae10-12a733412d11 {list_id: f352cc26-5127-4aba-96ed-88d86ce09464, created_at: 2024-10-31 22:24:38, description: Test 22, completed: 0, created_by: DEMO_USER_ID}>]>`
Here is the SQL for this:
```
    final results = await db.execute('''
      INSERT INTO
        lists(id, created_at, name, owner_id)
        VALUES(uuid(), datetime(), ?, ?)
      RETURNING *
      ''', [name, userId]);
```
Update Row:
`CrudTransaction<7, [CrudEntry<7/7 PATCH todos/b8087506-4cc0-432b-a169-42500a384187 {completed_at: 2024-10-31 22:25:14, completed: 1, completed_by: DEMO_USER_ID}>]>`
In this example I updated 3 fields, completed, completed_by and completed_at e.g.
```
    await db.execute(
        'UPDATE lists SET completed = TRUE, completed_by = ?, completed_at = datetime() WHERE id = ?',
        [userId, id]);
```

So, you're saying this is not the case for the PATCH events? Which version of the dart package are you using and could you share what your uploadData function looks like?
