### ISSUE TITLE
How can i connect powersyc with other backend with api

### ISSUE THREAD

**Issue by shiwam77** [powersync-ja/powersync.dart#49]
I don't want to directly write in HostedDatabase ,I will communicate with api then update the local & in offline fetch from local else from remote. If have these feature then plz give me one demo with flutter so that i will switch to Powersync

**Comment by DominicGBauer** [comment]
Hi @shiwam77 I'm not sure I completely understand what you are asking so want to confirm this is what you mean.

You want to use an API to handle updates to the DB and to use PowerSync to handle synchronising by communicating with the API to update the local on device sqlite DB?

**Comment by shiwam77** [comment]
yes
