### ISSUE TITLE
Feature Request: Integrate with drift package

### ISSUE THREAD

**Issue by hamishjohnson** [powersync-ja/powersync.dart#76]
I really like what Powersync offers, but I love the drift dynamic query builder functionality.

The drift query builder allows me to generate the SQL dynamically. I haven't thought deeply about how SQL could be dynamically generated manually if going the powersync route - but my initial impression is that it would be very difficult. I currently have my own custom sync functionality that does the job, but would like to replace it with something more battle tested. However - replacing drift's dynamic query building is not something I feel I can tackle.

It would be amazing if Powersync could work alongside drift

In this comment https://github.com/simolus3/drift/discussions/2880#discussioncomment-8363539 the creator of drift has showed interest in working on contributions that would make this feasible.

**Comment by rkistner** [comment]
That's already possible using [drift_sqlite_async](https://pub.dev/packages/drift_sqlite_async)!

See the example with powersync here: https://github.com/powersync-ja/powersync.dart/pull/60
