### ISSUE TITLE
No upsert available?

### ISSUE THREAD

**Issue by JCKodel** [powersync-ja/powersync.dart#94]
I created a schema with a user table.

When I try to upsert that table (`INSERT INTO users(bla bla bla) ON CONFLICT(id) DO UPDATE SET bla bla bla`), it says "while preparing statement, cannot UPSERT a view".

Checking the database, the `user` table is actually a view to `ps_table_user` (or something like this).

So, how to properly upsert a row (not using Drift)?

**Comment by cahofmeyr** [comment]
You're right that `UPSERT` /  `ON CONFLICT` is not supported. Unfortunately this is a limitation in SQLite that `ON CONFLICT` cannot be used on views, which is how PowerSync is structured currently.

One option is to use `INSERT OR REPLACE`, which is supported. It works a little differently, but this answer explains some options to get similar functionality: https://stackoverflow.com/a/4330694
